// traversy-media/vue-crash-2021/src/components/Header.vue
<script lang="ts">
import { defineComponent } from "vue"

export default defineComponent({
  name: "Header",
  props: {
    title: String,
    showAddForm: Boolean
  }
})
</script>

<template>
  <header>
    <h1>{{ showAddForm ? "Add Task" : title }}</h1>
    <button
      v-if="showAddForm === false"
      @click="$emit('toggleAddForm')"
      type="button"
      class="add btn"
    >
      Add Form
    </button>
    <button
      v-if="showAddForm === true"
      @click="$emit('toggleAddForm')"
      type="button"
      class="close btn"
    >
      Close
    </button>
  </header>
</template>

<style scoped>
header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

button[type="button"].add {
  background-color: #333;
  color: #666;
  border: 0;
}

button[type="button"].add:focus,
button[type="button"].add:hover {
  background-color: #333;
  color: #666;
  border: 0;
}

button[type="button"].close {
  background-color: #333;
  color: #666;
  border: 0;
}

button[type="button"].close:hover button[type="button"].close:focus {
  background-color: #333;
  color: #333;
  border: 0;
}
</style>

// traversy-media/angular-crash-2021/src/app/components/header/header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from "@angular/core"
import { Subscription } from "rxjs"
import { AuthService } from "src/app/services/auth.service"
import type { User } from "src/app/types"

@Component({
  selector: "app-header",
  template: `
    <header>
      <h1>{{ title }}</h1>
      <app-button
        color="var(--bgColor-300)"
        textColor="var(--textColor)"
        [text]="text"
        (btnClick)="hadleBtnClick()"
      ></app-button>
    </header>
  `,
  styles: [
    `
      header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 1em;
      }
    `
  ]
})
export class HeaderComponent implements OnInit {
  private readonly authService: AuthService

  public title = "Task Tracker"
  public text = "Add"

  authUser: User
  subscription: Subscription

  @Output() toggleFormOpen = new EventEmitter()
  @Input() isFormOpen: boolean

  constructor(authService: AuthService) {
    this.authService = authService
  }

  ngOnInit(): void {}

  hadleBtnClick() {
    // this.authService.setAuthUser(null)
    this.text = this.isFormOpen ? "Add" : "Close"
    this.toggleFormOpen.emit()
  }
}
